Replace chrono with time
slog-rs/bunyan pull request #11
Opened 2022-01-25 11:21 UTC by ShellWowza

Resolves `cargo audit` flagging this crate's dependencies as having vulnerabilities.

2022-02-10 19:36 UTC, Techcable commented
Hi. Thanks so much for this PR! This definitely needs to be done.

I've separated out the upgrade to Rust 2018 into a separate PR (#12)

One (small) question, why did you change the format for the times? Was there a specific reason or is it just convenience?

2022-02-10 20:29 UTC, Techcable commented on Cargo.toml
> +edition = "2018"
Why did you update to 2018 here?

~~Not criticizing, just curious.
In fact, I'll go separate this out into a separate commit right now~~

**EDIT:** I separated this out into PR #12

2022-02-10 20:29 UTC, Techcable commented on lib.rs
> +            .ok()
Why does this implicitly suppress errors here?

Are there alternatives?

2022-02-10 20:29 UTC, Techcable commented on lib.rs
> +                + "\"time\":\"2014-07-08T09:10:11Z\","
Hi! Why are we changing the time format here?

Is it just for convenience, or is there some other reason?

2022-02-10 21:17 UTC, Techcable commented on lib.rs
> +            .ok()
So looking at the time documentation, formatting errors can only happen if:
1. There is [`InsufficientTypeInformation`](https://docs.rs/time/latest/time/error/enum.Format.html#variant.InsufficientTypeInformation)
2. There is [`InvalidComponent`](https://docs.rs/time/latest/time/error/enum.Format.html#variant.InvalidComponent) 
3. There is an internal `std::io::Error`

None of these are really concerns for us 😉

2022-02-10 21:19 UTC, Techcable requested changes
Great job. I separated out the Rust 2018 changes into #11 

Only thing I'm concerned about is changing the time format.

2022-02-15 11:19 UTC, ShellWowza commented on lib.rs
> +                + "\"time\":\"2014-07-08T09:10:11Z\","
Hey, sorry, just got back to work from a long weekend. The reason here is simply a minor difference between chrono and time's implementation of RFC3339; Z and +00:00 are both valid timezone specifiers meaning the same thing per the standard. I could implement a custom format description which forces +00:00 instead; would this be prefered?

2022-02-18 08:54 UTC, ShellWowza commented on lib.rs
> +                + "\"time\":\"2014-07-08T09:10:11Z\","
References for this being correct:

[bunyan docs](https://www.npmjs.com/package/bunyan):

> `time`: Required. String. Added by Bunyan. Can be overridden. The date and time of the event in ISO 8601 Extended Format format and in UTC, as from [Date.toISOString()](https://developer.mozilla.org/en/JavaScript/Reference/Global_Objects/Date/toISOString).

[Date.prototype.toISOString()](https://developer.mozilla.org/en/JavaScript/Reference/Global_Objects/Date/toISOString):

> The toISOString() method returns a string in simplified extended ISO format ([ISO 8601](https://en.wikipedia.org/wiki/ISO_8601)), which is always 24 or 27 characters long (YYYY-MM-DDTHH:mm:ss.sssZ or ±YYYYYY-MM-DDTHH:mm:ss.sssZ, respectively). The timezone is always zero UTC offset, as denoted by the suffix "Z".

2022-02-20 02:14 UTC, Techcable commented on lib.rs
> +                + "\"time\":\"2014-07-08T09:10:11Z\","
Wow. I really appreciate the investigation here. Looks like you resolved a bug instead of introducing it :)

2022-02-20 02:15 UTC, Techcable approved these changes
Thanks so much for this. I really appreciate this PR :)

2022-02-20 02:17 UTC, merged

2022-02-20 02:30 UTC, Techcable commented
One thing to note is that this increases the Minimum Supported Rust Version from `1.38` to `1.53`.

I am 100% cool with this. However, this means next release we will need to:
1. Indicate this in the Changelog
2. bump the minor version from `2.3` -> `2.4`.

Additionally, I am also planning to switch from travis (broken) to Github Actions next release. That means we will never bump the MSRV by accident again 🎉 😄